; Boolean checks
DEF FALSE EQU 0
DEF TRUE  EQU 1

; flag operations
	const_def
	const FLAG_RESET ; 0
	const FLAG_SET   ; 1
	const FLAG_TEST  ; 2

; wOptions
DEF TEXT_DELAY_FAST    EQU %001 ; 1
DEF TEXT_DELAY_MEDIUM  EQU %011 ; 3
DEF TEXT_DELAY_SLOW    EQU %101 ; 5

	const_def 6
	const BIT_BATTLE_SHIFT     ; 6
	const BIT_BATTLE_ANIMATION ; 7

YELLOW_VERSION EQU 0
RED_VERSION    EQU 1
BLUE_VERSION   EQU 2
ANY_VERSION    EQU 3
RED_OR_BLUE    EQU 4

; wUniversalVariable values
USE_RED_OR_BLUE_GRAPHICS   EQU 42
VERSION_CHANGE_IN_PROGRESS EQU 69
